# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "708929f2fb4528d6eef438d7918e7d3a"
name = "Hydro-GWP"
handle = "hydro-gwp"
application_url = "https://gwp-2-6.vercel.app/"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,write_cart_transforms,read_discounts,write_discounts,read_customers,read_publications"

[auth]
redirect_urls = [
  "https://gwp-2-6.vercel.app/auth/callback",
  "https://gwp-2-6.vercel.app/auth/shopify/callback",
  "https://gwp-2-6.vercel.app/api/auth/callback"
]

[pos]
embedded = true
