# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "708929f2fb4528d6eef438d7918e7d3a"
name = "Hydro-GWP"
application_url = "https://gwp-2-6.vercel.app/"
embedded = true
handle = "hydro-gwp"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "discounts/create", "discounts/update", "discounts/delete" ]
  uri = "/webhooks/discounts"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_discounts,read_products,read_publications,write_cart_transforms,write_discounts,write_products"

[auth]
redirect_urls = [
  "https://gwp-2-6.vercel.app/auth/callback",
  "https://gwp-2-6.vercel.app/auth/shopify/callback",
  "https://gwp-2-6.vercel.app/api/auth/callback"
]
