query RunInput {
  cart {
    lines {
      id
      quantity
      cost {
        amountPerQuantity {
          amount
        }
      }
      merchandise {
        ... on ProductVariant {
          product {
            productType
          }
        }
      }
      etchInfo: attribute(key: "etchInfo") {
        key
        value
      }
      etchInfoHidden: attribute(key: "_etchInfo") {
        key
        value
      }
    }
  }
  discount {
    metafield(namespace: "free_etch", key: "config") {
      value
    }
    discountClasses
  }
}
