api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "bulk-discount-generator"
uid = "312143a9-08da-4278-887f-6f730d7e3116"
type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [[extensions.targeting]]
  target = "cart.delivery-options.discounts.generate.run"
  input_query = "src/cart_delivery_options_discounts_generate_run.graphql"
  export = "cart-delivery-options-discounts-generate-run"

  [extensions.input.variables]
  namespace = "bulk_discount"
  key = "variables"

  [extensions.build]
  command = ""
  path = "dist/index.wasm"

  [extensions.ui.paths]
  create = "/app/bulk-discount-generator/new"
  details = "/app/bulk-discount-generator/:id"
